OnlinePlatform/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings    # Make access to the settings.py to have access to the MEDIA_ROOT and MEDIA_URL
from django.conf.urls.static import static  # Create an url for a static file

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),  # Include urls from projects app
    path('', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) if DEBUG = false in settings.py

users/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.Profiles.as_view(), name="profiles"),
    path('profile/<str:pk>', views.UserProfile.as_view(), name="user-profile"),
    path('login/', views.LoginUser.as_view(), name="login"),
    path('logout/', views.LogoutUser.as_view(), name="logout"),
]

projects/models.py
from django.db import models
import uuid
from users.models import Profile


class Project(models.Model):
    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)    # Allow to create in database out this value and don't need to set description,
    featured_image = models.ImageField(null=True, blank=True, default="default.jpg")
    demo_link = models.CharField(max_length=2000, null=True, blank=True)
    source_link = models.CharField(max_length=2000, null=True, blank=True)
    tags = models.ManyToManyField('Tag', blank=True)    # class Tag will be found even when its under the class Project
    vote_total = models.IntegerField(default=0, null=True, blank=True)     # Votes set up to 0 at the beginning
    vote_ratio = models.IntegerField(default=0, null=True, blank=True)     # Whether vote was positive or negative
    created = models.DateTimeField(auto_now_add=True)    # When the project was added to db
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return self.title


class Review(models.Model):
    VOTE_TYPE = (
        ('up', 'Up Vote'),
        ('down', 'Down Vote'),
    )
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    body = models.TextField(null=True, blank=True)
    value = models.CharField(max_length=200, choices=VOTE_TYPE)
    created = models.DateTimeField(auto_now_add=True)  # Data created of review
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return self.value


class Tag(models.Model):
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)  # When the project was added to db
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return self.name

users/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(max_length=500, null=True, blank=True)
    username = models.CharField(max_length=200, null=True, blank=True)
    location = models.CharField(max_length=200, null=True, blank=True)
    short_intro = models.CharField(max_length=200, null=True, blank=True)
    bio = models.TextField(null=True, blank=True)
    profile_image = models.ImageField(blank=True, null=True, upload_to='profiles/', default='profiles/user-default.png')
    social_github = models.CharField(max_length=200, null=True, blank=True)
    social_twitter = models.CharField(max_length=200, null=True, blank=True)
    social_linkedin = models.CharField(max_length=200, null=True, blank=True)
    social_youtube = models.CharField(max_length=200, null=True, blank=True)
    social_website = models.CharField(max_length=200, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return str(self.username)  # if user doesn't exist that's need to be string method


class Skill(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return str(self.name)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.models import User
from django.views import View
from .models import Profile


# Create your views here.

class LoginUser(View):
    def get(self, request):

        if request.user.is_authenticated:
            return redirect('profiles')

        return render(request, 'users/login_register.html')

    def post(self, request):
        username = request.POST["username"]
        password = request.POST["password"]

        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, 'Username doesnt exist')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)  # Creates session for the user in db (in session table) its gonna add in browsers cookies
            return redirect('profiles')
        else:
            messages.error(request, 'Username OR password is incorrect')

        return render(request, 'users/login_register.html')


class LogoutUser(View):
    def get(self, request):
        logout(request)
        messages.error(request, 'User was logged out')
        return redirect('login')


class Profiles(View):
    def get(self, request):
        profiles = Profile.objects.all()
        context = {'profiles': profiles}
        return render(request, 'users/profiles.html', context)


class UserProfile(View):
    def get(self, request, pk):
        profile = Profile.objects.get(id=pk)

        topSkills = profile.skill_set.exclude(description__exact="")
        otherSkills = profile.skill_set.filter(description="")

        context = {'profile': profile, 'topSkills': topSkills, 'otherSkills': otherSkills}
        return render(request, 'users/user-profile.html', context)

    def post(self, request):
        pass

#
# class Profiles(View):
#     def get(self, request):
#         pass
#
#     def post(self, request):
#         pass

users/templates/users/login_register.html
{% extends 'main.html' %}

{% block content %}
    <form action="{% url 'login' %}" method="POST">
        {% csrf_token %}
        <label>
            <input type="text" name="username" placeholder="Username" />
            <input type="password" name="password" placeholder="Enter password" />
            <input type="submit" value="Login" />
        </label>
    </form>

{% endblock %}

users/templates/users/profiles.html
{% extends 'main.html' %}

{%  block content %}

  <!-- Main Section -->
  <main class="home">
    <section class="hero-section text-center">
      <div class="container container--narrow">
        <div class="hero-section__box">
          <h2>CONNECT WITH <span>DEVELOPERS</span></h2>
          <h2>FROM AROUND THE WORLD</h2>
        </div>

        <div class="hero-section__search">
          <form class="form" action="#" method="get">
            <div class="form__field">
              <label for="formInput#search">Search Developers </label>
              <input class="input input--text" id="formInput#search" type="text" name="text"
                placeholder="Search by developer name" />
            </div>

            <input class="btn btn--sub btn--lg" type="submit" value="Search" />
          </form>
        </div>
      </div>
    </section>

    <!-- Search Result: DevList -->
    <section class="devlist">
      <div class="container">
        <div class="grid grid--three">
          {% for profile in profiles %}
            <div class="column card">
                <div class="dev">
                  <a href="{% url 'user-profile' profile.id %}" class="card__body">
                    <div class="dev__profile">
                      <img class="avatar avatar--md" src="{{ profile.profile_image.url }}" alt="image" />
                      <div class="dev__meta">
                        <h3>{{ profile.name }}</h3>
                        <h5>{{ profile.short_intro|slice:"60" }}</h5>
                      </div>
                    </div>
                    <p class="dev__info"> {{ profile.bio|slice:"150" }} </p>
                    <div class="dev__skills">
                      {% for skill in profile.skill_set.all|slice:"5" %}
                          <span class="tag tag--pill tag--main">
                            <small>{{ skill }}</small>
                          </span>
                      {% endfor %}
                    </div>
                  </a>
                </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </section>
  </main>


{% endblock content %}

users/templates/users/user-profile.html
{% extends 'main.html' %}

{% block content %}
      <!-- Main Section -->
  <main class="profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <img class="avatar avatar--xl" src="{{ profile.profile_image.url }}" />
              <h2 class="dev__name">{{ profile }}</h2>
              <p class="dev__title">{{ profile.short_intro}}</p>
              <p class="dev__location">Based in {{ profile.location }}</p>
              <ul class="dev__social">

                {% if profile.social_github %}
                    <li>
                      <a title="Github" href="{{ profile.social_github }}" target="_blank"><i class="im im-github"></i></a>
                    </li>
                {% endif %}

                {% if profile.social_twitter %}
                    <li>
                      <a title="Twitter" href="{{ profile.social_twitter }}" target="_blank"><i class="im im-twitter"></i></a>
                    </li>
                {% endif %}

                {% if profile.social_linkedin %}
                    <li>
                      <a title="LinkedIn" href="{{ profile.social_linkedin }}" target="_blank"><i class="im im-linkedin"></i></a>
                    </li>
                {% endif %}

                {% if profile.social_website %}
                    <li>
                      <a title="Personal Website" href="{{ profile.social_website }}" target="_blank"><i class="im im-globe"></i></a>
                    </li>
                {% endif %}

              </ul>
              <a href="#" class="btn btn--sub btn--lg">Send Message </a>
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">
                {{ profile.bio }}
            </p>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Skills</h3>
            <div class="devInfo__skills">

              {% for skill in topSkills %}
                  <div class="devSkill">
                    <h4 class="devSkill__title"> {{ skill.name }} </h4>
                    <p class="devSkill__info"> {{ skill.description }} </p>
                  </div>
              {% endfor %}

              <h3 class="devInfo__subtitle">Other Skills</h3>
              <div class="devInfo__otherSkills">

                {% for skill in otherSkills %}

                    <span class="tag tag--pill tag--sub tag--lg">
                      <small>{{ skill.name }}</small>
                    </span>

                {% endfor %}

              </div>
            </div>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Projects</h3>
            <div class="grid grid--two">
              {% for project in profile.project_set.all %}
                <div class="column">
                <div class="card project">
                  <a href="{% url 'project' project.id %}" class="project">
                    <img class="project__thumbnail" src="{{ project.featured_image.url }}" alt="project thumbnail" />
                    <div class="card__body">
                      <h3 class="project__title">{{ project.title }}</h3>
                      <p><a class="project__author" href="">By {{ project.owner.name }}</a></p>
                      <p class="project--rating">
                        <span style="font-weight: bold;">{{ project.vote_ratio }}%</span> Positive
                        Feedback ({{ project.vote_total }} Vote{{ project.vote_total|pluralize:"s" }})
                      </p>
                      <div class="project__tags">
                        {% for tag in project.tags.all %}
                            <span class="tag tag--pill tag--main">
                                <small>{{ tag }}</small>
                            </span>
                        {% endfor %}
                      </div>
                    </div>
                  </a>
                </div>
                </div>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}